# Generated by Django 5.2.5 on 2025-08-27 23:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('m2_construidos', models.FloatField(default=0)),
                ('m2_totales', models.FloatField(default=0)),
                ('estacionamientos', models.PositiveSmallIntegerField(default=0)),
                ('habitaciones', models.PositiveSmallIntegerField(default=0)),
                ('banos', models.PositiveSmallIntegerField(default=0)),
                ('direccion', models.CharField(max_length=100)),
                ('precio_inmueble', models.DecimalField(decimal_places=2, max_digits=8)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('tipo_de_inmueble', models.CharField(choices=[('CASA', 'casa'), ('DEPARTAMENTO', 'departamento'), ('PARCELA', 'parcela')], max_length=20)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inmuebles', to='portal.comuna')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inmuebles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
