# Generated by Django 5.2.5 on 2025-09-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_solicitudarriendo_arrendatario'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='imagen',
            field=models.ImageField(default='sin_imagen/', upload_to='inmuebles/'),
        ),
    ]
