# Generated by Django 5.2.5 on 2025-09-02 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_inmueble_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiluser',
            name='imagen',
            field=models.ImageField(default='default_profile.png', upload_to='foto_perfil/'),
        ),
    ]
